nodeLinker: node-modules

# Enable workspace hoisting to deduplicate dependencies
enableGlobalCache: true

# Improve dependency resolution - use more aggressive hoisting
nmHoistingLimits: workspaces  

# Ensure consistent peer dependencies
enableTransparentWorkspaces: false

# Improve Turborepo compatibility
compressionLevel: 0

# Better dependency deduplication
nmMode: hardlinks-local

# Faster installation
enableImmutableInstalls: false

# Better conflict resolution
enableProgressBars: true
preferInteractive: true
