
// TODO This was auto generated by SvelteKit. What does it do?
// import type { LayoutLoad } from './$types';

// export const load = (async () => {
//     return {};
// }) satisfies LayoutLoad;

export const prerender = true